name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  crda-analysis-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: pre-action-setup.yaml
        run: |
          pwd
          ls -l
          mkdir -p site-dir
          pip3 install --target=site-dir -r requirements.txt --upgrade
      
      - name: crda-analysis
        uses: jparsai/cdra-analysis/python-3.6@main
        with:
          manifest-file-path: requirements.txt
          output-file-path: result.json
          pkg-installation-directory-path: site-dir
        env:
          CRDA_KEY: ${{ secrets.CRDA_KEY }}
      
      - name: post-action-setup
        run: |
          pwd
          ls -l
          cat result.json
