name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  setup-env:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jparsai/crdaimagev2:latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-env
        run: |
          pwd
          ls -l
          mkdir -p /__w/test/test/site-dir
          ls -l
          pip3 install --target=/__w/test/test/site-dir -r requirements.txt --upgrade
          echo ============================================
          pip3 show flask
      - name: crda test
        uses: jparsai/test@master
        with:
          manifest-file-path: /github/workspace/requirements.txt
          output-file-path: /github/workspace/result.json
          pkg-installation-directory-path: /__w/test/test/site-dir
          image: quay.io/jparsai/crdaimagev2:latest
        env:
          CRDA_KEY: ${{ secrets.CRDA_KEY }}
      - name: check-dir
        run: |
          ls /__w/test/test
          pip3 show flask

