name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: test locally
    steps:
      - name: crda test
        uses: jparsai/test@master
