name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  setup-env:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jparsai/crdaimagev1:latest
      env:
        AUTH_TOKEN: 9e7da76708fe374d8c10fa752e72989f
        CRDA_KEY: 11b3f460-29ca-42a0-91ce-c1c5ec4a1bf3
        HOST: https://f8a-analytics-2445582058137.production.gw.apicast.io:443
    steps:
      - uses: actions/checkout@v2
      - name: setup-env
        run: pip3 install -r requirements.txt
      - name: crda-report
        run: crda analyse /__w/test/test/requirements.txt
