name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  crda-analysis-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pre-action-setup.yaml
        run: |
          mkdir -p $GITHUB_WORKSPACE/site-dir
          pip3 install --target=$GITHUB_WORKSPACE/site-dir -r requirements.txt --upgrade
      - name: crda-analysis
        uses: jparsai/cdra-analysis/python-3.6@main
        with:
          manifest-file-path: "$GITHUB_WORKSPACE/requirements.txt"
          output-file-path: "$GITHUB_WORKSPACE/result.json"
          pkg-installation-directory-path: "$GITHUB_WORKSPACE/site-dir/"
        env:
          CRDA_KEY: ${{ secrets.CRDA_KEY }}
      - name: post-action-setup
        run: |
          cat $GITHUB_WORKSPACE/result.json

