name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  crda-job:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jparsai/crdaimagev1:latest
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        CRDA_KEY: ${{ secrets.CRDA_KEY }}
        HOST: ${{ secrets.HOST }}
    steps:
      - uses: actions/checkout@v2
      #- name: setup-env
      #  run: pip3 install -r requirements.txt
      - name: crda-report
        run: get_pypi_report
        #run: crda analyse /__w/test/test/requirements.txt
        #run: get_pypi_report / /__w/test/test requirements.txt total_vulnerabilites 1 result4.json
