name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  setup-env:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jparsai/crdaimagev1:latest
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        CRDA_KEY: ${{ secrets.CRDA_KEY }}
        HOST: ${{ secrets.HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: setup-env
        run: |
          echo 11------------
          echo ${{ secrets.AUTH_TOKEN }}
          echo ${{ secrets.CRDA_KEY }}
          echo ${{ secrets.HOST }}
          echo 22------------
          pip3 install -r requirements.txt
      - name: crda-report
        run: crda analyse /__w/test/test/requirements.txt
