name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  crda-job:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jparsai/crdaimagev1:latest
    steps:
      - name: crda-report
        with:
          MY_NAME: "testing"
          script: |
              echo 'hello from function1.'
              echo 'hello from $MY_NAME'
