name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  crda-job:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jparsai/crdaimagev1:latest
    steps:
      - name: crda-report
        run: |
          echo 'hello from function1.'
          printf "CRDA Analysis task is being executed.\n"
          sh /crda_dir/crda.sh 
          printf "\nCRDA Analysis task is completed."
