name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  setup-env:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jparsai/crdaimagev1:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python dependencies
        run: |
          pwd
          ls -l
          pip3 install -r requirements.txt
  crda-report:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jparsai/crdaimagev1:latest
    steps:
      - run: cat /etc/os-release
