name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  setup-env:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jparsai/crdaimagev1:latest
      env:
        AUTH_TOKEN: 9e7da76708fe374d8c10fa752e72989f_1112
        CRDA_KEY: 11b3f460-29ca-42a0-91ce-c1c5ec4a1bf3_1112
        HOST: https://f8a-analytics-2445582058137.production.gw.apicast.io:443_1112
    steps:
      - uses: actions/checkout@v2
      - name: setup-env
        run: |
          echo ${AUTH_TOKEN}
          echo ${CRDA_KEY}
          echo ${HOST}
          pip3 install -r requirements.txt
      - name: crda-report
        run: crda analyse /__w/test/test/requirements.txt
