name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  setup-env:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jparsai/crdaimagev1:latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-env
        run: pip3 install -r requirements.txt
      - name: crda-report
        run: crda analyse /__w/test/test/requirements.txt
