name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  setup-env:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jparsai/crdaimagev2:latest
      env:
        CRDA_KEY: ${{ secrets.CRDA_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: crda test
        uses: jparsai/test@master
        with:
          manifest-file-path: /github/workspace/requirements.txt
          output-file-path: /github/workspace/result.json
          pkg-installation-directory-path: /github/workspace
          image: quay.io/jparsai/crdaimagev2:latest
          
