name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  setup-env:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jparsai/crdaimagev1:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python dependencies
        run: pip3 install -r requirements.txt
      - name: crda-report
        run: |
          pwd
          echo 1----------------------------
          ls -l
          echo 2----------------------------
          cat requirements.txt
          echo 3----------------------------
          crda analyse /__w/test/test/requirements.txt
