name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  crda-analysis-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pre-action-setup.yaml
        run: |
          mkdir -p /home/runner/work/test/test/site-dir
          pip3 install --target=/home/runner/work/test/test/site-dir -r requirements.txt --upgrade
      - name: crda-analysis
        uses: jparsai/cdra-analysis/python-3.6@main
        with:
          manifest-file-path: /github/workspace/requirements.txt
          output-file-path: /github/workspace/result.json
          pkg-installation-directory-path: /github/workspace/site-dir/
        env:
          CRDA_KEY: ${{ secrets.CRDA_KEY }}
      - name: post-action-setup
        run: |
          cat /home/runner/work/test/test/result.json
